# Student Project

In [1]:
import sys
from pathlib import Path
import pandas as pd

from students import generate_students
from analysis import calculate_class_statistics, save_report

## 1. Generate Students Data

In [2]:
students = generate_students(10)
df = pd.DataFrame(students)
df

student_id birth_date               grades  age  average
    STD001 2004-09-16 [17.59, 12.47, 3.74]   22    11.27
    STD002 2000-10-27   [2.52, 3.17, 17.2]   25     7.63
    STD003 2003-12-21  [4.73, 5.43, 17.42]   22     9.19
    STD004 2005-09-24   [1.17, 9.0, 12.57]   21     7.58
    STD005 2004-05-02  [4.87, 11.97, 5.67]   22     7.50
    STD006 2006-07-04   [7.35, 1.73, 5.62]   20     4.90
    STD007 2006-03-13   [5.92, 11.89, 9.3]   20     9.04
    STD008 2001-08-25 [2.68, 15.32, 12.47]   25    10.16
    STD009 2001-05-29 [7.56, 14.36, 14.09]   25    12.00
    STD010 2003-08-20   [5.8, 3.12, 16.96]   23     8.63

## 2. Statistical Analysis

In [3]:
stats = calculate_class_statistics(students)
stats_df = pd.DataFrame(list(stats.items()), columns=["Metric", "Value"])
stats_df

            Metric  Value
              mean   8.79
            median   8.84
standard_deviation   2.06
       min_average   4.90
       max_average  12.00
          mean_age  22.50

## 3. Save Report

In [4]:
save_report(students, stats, "results/report.txt")

with open("results/report.txt", "r", encoding="utf-8") as f:
    print(f.read())

STUDENT REPORT
------------------------------------------------------------
ID         | Birth Date   | Age   | Grades               | Average
------------------------------------------------------------
STD001     | 2004-09-16   | 22    | 17.59, 12.47, 3.74   | 11.27
STD002     | 2000-10-27   | 25    | 2.52, 3.17, 17.20    | 7.63
STD003     | 2003-12-21   | 22    | 4.73, 5.43, 17.42    | 9.19
STD004     | 2005-09-24   | 21    | 1.17, 9.00, 12.57    | 7.58
STD005     | 2004-05-02   | 22    | 4.87, 11.97, 5.67    | 7.50
STD006     | 2006-07-04   | 20    | 7.35, 1.73, 5.62     | 4.90
STD007     | 2006-03-13   | 20    | 5.92, 11.89, 9.30    | 9.04
STD008     | 2001-08-25   | 25    | 2.68, 15.32, 12.47   | 10.16
STD009     | 2001-05-29   | 25    | 7.56, 14.36, 14.09   | 12.00
STD010     | 2003-08-20   | 23    | 5.80, 3.12, 16.96    | 8.63
------------------------------------------------------------

CLASS STATISTICS
------------------------------------------------------------
Mean Average:       8.79
Median Average:     8.84
Standard Deviation: 2.06
Min Average:        4.90
Max Average:        12.00
Mean Age:           22.50